### ISSUE TITLE
Accelの処理速度低下（推測）に関して相談

### ISSUE THREAD

**Issue by kazumia** [kazumia/Accel-modify-request#1]
依頼者：山崎さん

ひとまず、取り急ぎの対応策として
「フォームのみを印刷する」のチェックを外していただくことを検討しましたが、Gluegentの設計上それが不可能ということで
伝票番号をフォーム上に表示できるようにしていだだくことは可能でしょうか。

https://gluegent-workflow.appspot.com/console.html#print/900004/7241213020/7234613486/false

（添付の伝票だと、起案者と伝票番号も無く、有象無象の中から金額や負担部署を頼りに探すことをしております。。）

お手数おかけしますがよろしくお願いします。

mail ID:
https://mail.google.com/mail/ca/u/0/#label/KEIRI/WhctKJVJcmJJMVLxNZRvDVPPvKGnLXVGBpvQGClMLzmCqnzRfhKWxSSqQSDHlbdXGvLpFBL

**Comment by mihonaka** [comment]
GoogleとのAPI連携に起因した一時的なもので、
すでに対応済みでした
